### ISSUE TITLE
putting Armor on undeath horses

### ISSUE THREAD

**Issue by thiefa** [EasyMFnE/DeadHorses#3]
hi, 
is there any way you could make the undeath horses can wear armor?
its pretty unsave ridding without some nice and shiny armor ;)

ty

**Comment by EasyMFnE** [comment]
Duplicate of Issue #1.
If you go there, you can see the results of every way I tried to get around it.  The armor, even if forcibly equipped via code, is not rendered and does not protect against damage at all.

I'm leaving this issue open for the time being.  I may look into making a simple client modification to render undead horses' armor.  If so, I will revisit the plugin and add in (optional) functionality that could allow users to equip them.

**Comment by EasyMFnE** [comment]
Made some PAINFUL progress in the clientside rendering of armor on undead/skeleton horses.
Normal undead horse shown wearing armor as rendered by the client:
![Awful](http://i.imgur.com/OjgndBp.png)
Fixed via event injection transformers: 
![Skeleton horse with diamond armor](http://i.imgur.com/P1CzDMW.png)
The way the rendering is written and how the LayeredTextures are set up makes me want to tear my hair out.  Next feasibility hurdle is that in multiplayer (screenshots are from single player) the server is not sending the armor index to the client for dead horses.

**Comment by thiefa** [comment]
Hi, 
thank you verry mutch for trying that hard :)

if its not working its oke, just would have been nice to have.

if i can help you in any way im able to do, let me know.
could offer you my server to test it out, helping to program is way off my abilities...

**Comment by EasyMFnE** [comment]
@thiefa I believe I have the client-side functionality completed.  I've plopped it up on here as a new repository (HorseTweaks).  Later this week I'll take a look at making a new version of DeadHorses with the requested features if it can be done.

It's probably more work than it's worth, but I do enjoy a good puzzle... haha.
![2014-10-29_13 48 45](https://cloud.githubusercontent.com/assets/3160455/4834222/9f151d2e-5fab-11e4-8037-04990bbfd1a9.png)

**Comment by EasyMFnE** [comment]
New pre-release version of 1.2.0 [here](https://github.com/EasyMFnE/DeadHorses/releases/tag/v1.2.0).
Adds ability to equip dead horses with barding, and makes sure the barding affects damage calculations.  Personally tested, but could use some additional testing before I take off the "alpha" suffix.

Barding does not render, due to limitations in Minecraft itself.  This issue will be addressed via this plugin and [HorseTweaks](https://github.com/EasyMFnE/HorseTweaks) as needed when I make more progress on that front.

**Comment by thiefa** [comment]
hi, 
i just dl 1.2.0 from the link above, but i still cant put any armor on the horse.
sorry, if i got something wrong.

as a sidenote:
the link you posted on dev.bukkit.com for you extension "horsetweaks" dont work.
you made a / instead a . between github and com.

**Comment by thiefa** [comment]
if it helps, i invite you to my server so we can test it online..
just drop me a line, and ill open a small one for testing purposes.

**Comment by EasyMFnE** [comment]
Did you remove the DeadHorses config.yml so it generates a new one?
You must do that or manually add the config nodes, because the defaults are 'false'.

Thanks for the heads-up about the broken link.  I'll fix that now.

**Comment by thiefa** [comment]
ups.
no did not remove the old config.. my bad.. should have known....
after removing i can put the armor on :)

however, when i put the armor on a undead/skeleton horse, it gets invisible aslong as it wears the armor. this gets adressed via horsetweaks, right? 

cant compile horetweaks on my own, didnt ever work with java, so i canot state anything about it...

**Comment by EasyMFnE** [comment]
The armor will be invisible until you enable packet modification in the config (normally the servers don't even send the armor metadata for undead horses to the clients).  Then, the undead horses will show up as pure white on the client (because the client doesn't expect the armor metadata from the server, because derp).  HorseTweaks can fix that rendering issue.  I have a release [here](https://github.com/EasyMFnE/HorseTweaks/releases/tag/v1.0.0-alpha).  It requires LiteLoader, which is by far the best mod loader from my development experience.  It's marked as Alpha, but only because it's not been tested by anyone other than myself.

Edit: It's worth noting that all of this is because of Minecraft being so derpy behind the scenes.

**Comment by thiefa** [comment]
i have packet modification enabled.

what happens if i put an armor on the horse is that the entire horse gets invisible.
its not just the armor that dosent get rendert.

maybe a difference in singelplayer and server side? or minecraft versions? running on a bukkit 1.7.9 r3..
will try with the liteloader to see what happens then.

**Comment by thiefa** [comment]
running with liteloader and your horsetweak i can see the armor and the undead/skeleton horse.
all works nicely that way :)

**Comment by EasyMFnE** [comment]
Glad that it all came together!  If you run into any issues with HorseTweaks, let me know via a new Issue (or if you have any suggestions).
